### ISSUE TITLE
Incomplete Code

### ISSUE THREAD

**Issue by CaptSeagull** [uselesscookies/reimagined-octo-sniffle#1]
Line 89. Student object has not been inserted to the main object yet.

**Comment by uselesscookies** [comment]
> 
> 
> Line 89. Student object has not been inserted to the main object yet.

What do you mean?

**Comment by CaptSeagull** [comment]
> 
> 
> > Line 89. Student object has not been inserted to the main object yet.
> 
> What do you mean?

Notice that you made a student object, but you arent doing anything to it. The student object is not added to the array yet (for searching and deleting). You need to use the insert method for it.

**Comment by uselesscookies** [comment]
> 
> 
> > > Line 89. Student object has not been inserted to the main object yet.
> > 
> > 
> > What do you mean?
> 
> Notice that you made a student object, but you arent doing anything to it. The student object is not added to the array yet (for searching and deleting). You need to use the insert method for it.

Should the insert method be static? I'm getting an error message for that.

**Comment by CaptSeagull** [comment]
> 
> 
> > > > Line 89. Student object has not been inserted to the main object yet.
> > > 
> > > 
> > > What do you mean?
> > 
> > 
> > Notice that you made a student object, but you arent doing anything to it. The student object is not added to the array yet (for searching and deleting). You need to use the insert method for it.
> 
> Should the insert method be static? I'm getting an error message for that.

It shouldn't no. You have MainClass object in line 66. You can just use that for it.
