### ISSUE TITLE
Student class

### ISSUE THREAD

**Issue by CaptSeagull** [uselesscookies/reimagined-octo-sniffle#2]
line  25: Non-static methods are being called in a static method. If possible, try to also error check if the passed Student object is null.

**Comment by uselesscookies** [comment]
> 
> 
> line 25: Non-static methods are being called in a static method. If possible, try to also error check if the passed Student object is null.

How do I do this?

**Comment by CaptSeagull** [comment]
> 
> 
> > line 25: Non-static methods are being called in a static method. If possible, try to also error check if the passed Student object is null.
> 
> How do I do this?

Notice that you are passing a Student object "a" And that you use it to call a.getID(). Same principle for the others. Now as for the null part, you can cover that print line with a condition `if(a != null)`

**Comment by uselesscookies** [comment]
> 
> 
> > > line 25: Non-static methods are being called in a static method. If possible, try to also error check if the passed Student object is null.
> > 
> > 
> > How do I do this?
> 
> Notice that you are passing a Student object "a" And that you use it to call a.getID(). Same principle for the others. Now as for the null part, you can cover that print line with a condition `if(a != null)`

I don't use "getID" for the first part because ID is an int only in the Student class, but I think I get what you mean?
`public static void printInfo(Student a) {
		if (a != null) {
			System.out.print("ID: " + a.ID + " Name: " + a.getName() + " Age: " + a.getAge());
		} else {
			System.out.print("");
		}

	}`
Like this?
