### ISSUE TITLE
MainClass class

### ISSUE THREAD

**Issue by CaptSeagull** [uselesscookies/reimagined-octo-sniffle#3]
line 16: 
`System.out.println(studentArray[i]);`
Preferably should use Student's printInfo(...) method (See Student.java) to print out the student infos.

**Comment by CaptSeagull** [comment]
lines 28-31: Should display this error message **after** the loop ends not during. Current logic will result in only checking one item in the list.

**Comment by CaptSeagull** [comment]
lines 28-31: Should also check if item is null to prevent exceptions.

**Comment by CaptSeagull** [comment]
line 41: errors out at j=0. The items are moving to the right. Why?

**Comment by CaptSeagull** [comment]
line 56: If student exists, you can escape the loop (since a duplicate should not be added at all).
lines 57-59: Should display this error message **after** the loop ends not during. Current logic will not loop through all the items on the list safely.

**Comment by CaptSeagull** [comment]
line 55: Needs to be an else if. Once the code in 54 happens, it will reach line 56 and generate that error message even tho the student was just added.

**Comment by CaptSeagull** [comment]
line 53: Since a student was added here, the loop needs to break or else the loop will continue keep generating the error line at 56

**Comment by CaptSeagull** [comment]
line 94: is the search method needed?

For searchStudent(...) and deleteStudent(...) methods, you can add a print line stating the code was successful to inform the user.

**Comment by CaptSeagull** [comment]
Line 9-10: Preferably these variables shouldn't be static as they are only used on the main method. They should be only declared there. It can potentially lead to coding errors if they are kept static.

**Comment by uselesscookies** [comment]
> 
> 
> line 41:
> `for (int j = 0; j < studentArray.length; j++) {`
> `studentArray[j] = studentArray[j - 1];`
> errors out at j=0.
> 
> The items are moving to the right. Why?

I want to make them move to the left so that after deletion they fill in the empty spots.

**Comment by uselesscookies** [comment]
> 
> 
> lines 28-31: Should also check if item is null to prevent exceptions.

I'm thinking about making an else if statement so that it ignores the nulls, but how do I do that without just writing another for loop?

**Comment by CaptSeagull** [comment]
> 
> 
> > line 41:
> > `for (int j = 0; j < studentArray.length; j++) {`
> > `studentArray[j] = studentArray[j - 1];`
> > errors out at j=0.
> > The items are moving to the right. Why?
> 
> I want to make them move to the left so that after deletion they fill in the empty spots.

then two things. instead of `j = 0` you go `j = i` since thats when the deletion happened. We dont need to move the items before the item correct?
Then finally to move to the left should be `studentArray[j] = studentArray[j + 1];`



> 
> 
> > lines 28-31: Should also check if item is null to prevent exceptions.
> 
> I'm thinking about making an else if statement so that it ignores the nulls, but how do I do that without just writing another for loop?

Yes, at the start of the loop and before that first if statement you can check there. so
```if(studentArray[i] == null) {
   continue;
}
```

**Comment by uselesscookies** [comment]
> 
> 
> line 56:
> `System.out.println("Student cannot be created because IDs match.")`
> If student exists, you can escape the loop (since a duplicate should not be added at all).
> 
> lines 57-59:
> `System.out.println("The student database is full! Cannot fit anymore students!"); break;`
> Should display this error message **after** the loop ends not during. Current logic will not loop through all the items on the list safely.

For lines 57-59, I tried putting it after the break statement but it can't reach that spot. How do I do that without putting it immediately after the loop is called in the main method (unless I'm supposed do that and am overlooking something)?

**Comment by CaptSeagull** [comment]
> 
> 
> > line 56:
> > `System.out.println("Student cannot be created because IDs match.")`
> > If student exists, you can escape the loop (since a duplicate should not be added at all).
> > lines 57-59:
> > `System.out.println("The student database is full! Cannot fit anymore students!"); break;`
> > Should display this error message **after** the loop ends not during. Current logic will not loop through all the items on the list safely.
> 
> For lines 57-59, I tried putting it after the break statement but it can't reach that spot. How do I do that without putting it immediately after the loop is called in the main method (unless I'm supposed do that and am overlooking something)?

needs to be after the loop itself
so looks like this 
```java
             for (int i = 0; i < studentArray.length; i++) {
			if (studentArray[i] == null) {
				studentArray[i] = student;
			}
			if (student == studentArray[i]) {
				System.out.println("Student cannot be created because IDs match.");
			} else {
				
				break;
			}
		}
        System.out.println("The student database is full! Cannot fit anymore students!");
```

**Comment by uselesscookies** [comment]
> 
> 
> line 94:
> `main.searchStudent(ID);`
> is the search method needed?
> 
> For searchStudent(...) and deleteStudent(...) methods, you can add a print line stating the code was successful to inform the user.

search method is mandatory, as I need to display the student being deleted before they're deleted.

**Comment by CaptSeagull** [comment]
> 
> 
> > > line 56:
> > > `System.out.println("Student cannot be created because IDs match.")`
> > > If student exists, you can escape the loop (since a duplicate should not be added at all).
> > > lines 57-59:
> > > `System.out.println("The student database is full! Cannot fit anymore students!"); break;`
> > > Should display this error message **after** the loop ends not during. Current logic will not loop through all the items on the list safely.
> > 
> > 
> > For lines 57-59, I tried putting it after the break statement but it can't reach that spot. How do I do that without putting it immediately after the loop is called in the main method (unless I'm supposed do that and am overlooking something)?
> 
> needs to be after the loop itself
> so looks like this
> 
> ```java
>              for (int i = 0; i < studentArray.length; i++) {
> 			if (studentArray[i] == null) {
> 				studentArray[i] = student;
> 			}
> 			if (student == studentArray[i]) {
> 				System.out.println("Student cannot be created because IDs match.");
> 			} 
> 		}
>         System.out.println("The student database is full! Cannot fit anymore students!");
> ```

now you may ask, what about when the code reaches `studentArray[i] = student;` or `if (student == studentArray[i])` you can add a `return;` line after them.



> 
> 
> > line 94:
> > `main.searchStudent(ID);`
> > is the search method needed?
> > For searchStudent(...) and deleteStudent(...) methods, you can add a print line stating the code was successful to inform the user.
> 
> search method is mandatory, as I need to display the student being deleted before they're deleted.

oh ok , then you may need to add a line after you found the student in search(...) to print out that you found it or by using the printInfo from the student class

**Comment by uselesscookies** [comment]
> 
> 
> Line 9-10:
> `static int num, age = 0;`
> `static String ID, name = "";`
> 
> Preferably these variables shouldn't be static as they are only used on the main method. They should be only declared there. It can potentially lead to coding errors if they are kept static.

making them non-static gives an error: Cannot make static reference to non-static field [name of variable]

**Comment by CaptSeagull** [comment]
> 
> 
> > Line 9-10:
> > `static int num, age = 0;`
> > `static String ID, name = "";`
> > Preferably these variables shouldn't be static as they are only used on the main method. They should be only declared there. It can potentially lead to coding errors if they are kept static.
> 
> making them non-static gives an error: Cannot make static reference to non-static field [name of variable]

yes, you need to declare them inside the main method instead. not there on the class level.

**Comment by CaptSeagull** [comment]
> 
> 
> > > Line 9-10:
> > > `static int num, age = 0;`
> > > `static String ID, name = "";`
> > > Preferably these variables shouldn't be static as they are only used on the main method. They should be only declared there. It can potentially lead to coding errors if they are kept static.
> > 
> > 
> > making them non-static gives an error: Cannot make static reference to non-static field [name of variable]
> 
> yes, you need to declare them inside the main method instead. not there on the class level.

I would personally place them before the do-while loop. 
```java
        int num, age = 0;
	String ID, name = "";
        do {
```

**Comment by uselesscookies** [comment]
> 
> 
> > > line 41:
> > > `for (int j = 0; j < studentArray.length; j++) {`
> > > `studentArray[j] = studentArray[j - 1];`
> > > errors out at j=0.
> > > The items are moving to the right. Why?
> > 
> > 
> > I want to make them move to the left so that after deletion they fill in the empty spots.
> 
> then two things. instead of `j = 0` you go `j = i` since thats when the deletion happened. We dont need to move the items before the item correct?
> Then finally to move to the left should be `studentArray[j] = studentArray[j + 1];`
> 
> > > lines 28-31: Should also check if item is null to prevent exceptions.
> > 
> > 
> > I'm thinking about making an else if statement so that it ignores the nulls, but how do I do that without just writing another for loop?
> 
> Yes, at the start of the loop and before that first if statement you can check there. so
> 
> ```
> if(studentArray[i] == null) {
>    continue;
> }
> ```

Is this okay?
`@Override // searches every student in the array
	public void searchStudent(String ID) {
		int c = Integer.parseInt(ID);
		for (int i = 0; i < studentArray.length; i++) {
			if (studentArray[i] == null) {
				continue;
			}
			if (c == studentArray[i].getID()) {
				Student.printInfo(studentArray[i]);
				break;
			} else {
				break;
			}
		}
		System.out.println("Cannot find student with that ID."); // moved from line 29 to 32
	}`

**Comment by CaptSeagull** [comment]
> 
> 
> > > > line 41:
> > > > `for (int j = 0; j < studentArray.length; j++) {`
> > > > `studentArray[j] = studentArray[j - 1];`
> > > > errors out at j=0.
> > > > The items are moving to the right. Why?
> > > 
> > > 
> > > I want to make them move to the left so that after deletion they fill in the empty spots.
> > 
> > 
> > then two things. instead of `j = 0` you go `j = i` since thats when the deletion happened. We dont need to move the items before the item correct?
> > Then finally to move to the left should be `studentArray[j] = studentArray[j + 1];`
> > > > lines 28-31: Should also check if item is null to prevent exceptions.
> > > 
> > > 
> > > I'm thinking about making an else if statement so that it ignores the nulls, but how do I do that without just writing another for loop?
> > 
> > 
> > Yes, at the start of the loop and before that first if statement you can check there. so
> > ```
> > if(studentArray[i] == null) {
> >    continue;
> > }
> > ```
> 
> Is this okay?
> 
> ```
> 	public void searchStudent(String ID) {
> 		int c = Integer.parseInt(ID);
> 		for (int i = 0; i < studentArray.length; i++) {
> 			if (studentArray[i] == null) {
> 				continue;
> 			}
> 			if (c == studentArray[i].getID()) {
> 				Student.printInfo(studentArray[i]);
> 				break;
> 			} else {
> 				break;
> 			}
> 		}
> 		System.out.println("Cannot find student with that ID."); // moved from line 29 to 32
> 	}
> ```

sorry i guess my edit was too late. i was thinking like this
```java
@Override 
// searches every student in the array 
public void searchStudent(String ID) {
	int c = Integer.parseInt(ID);
	for (int i = 0; i < studentArray.length; i++) {
		if (studentArray[i] == null) {
			continue;
		}
		
		if (c == studentArray[i].getID()) {
			Student.printInfo(studentArray[i]);
			return; // break; use return instead of break
		} // else {
		//	break;
		//}
	}
       System.out.println("Cannot find student with that ID.");
}```
